### PR TITLE
Hide invalid times

### LINKED ISSUE #30: Add grab'n'go option, and hide appearance of invalid meal times (i.e. no breakfast on berkshire, don't display grabngo when it's not there)

### PR DESCRIPTION
**Pull request by aflam745**
Only shows the meal types buttons for each dining hall

Closes #30

### CODE REVIEW

**Comment by odepoint** [comment]
still seems to be broken

**Comment by craigbsch** [comment]
ignore the reviewers thing I messed up

**Comment by craigbsch** [comment]
@aflam745 do you want me to take a look at this?

**Review by craigbsch — COMMENTED** [review]
Fixed functionality, now im fixing bug where the buttons gain a ton of height for no reason unless @aflam745 wants to finish this up

**Pull request merged**
